POST http://localhost:3000/pontos
Content-Type: application/json

{
  "employeeId": "rubinho_id"
}

###

GET http://localhost:3000/pontos

###

DELETE http://localhost:3000/pontos

###
GET http://localhost:3000/pontos/fernando_id

###

PATCH http://localhost:3000/pontos/fernando_id